//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nails_sack.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staffer
    {
        public int stafferID { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public string status { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
